networks:
  internal_net:
    driver: bridge

services:
  db:
    environment:
      MYSQL_DATABASE: client_management
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
    expose:
      - "3306"
    image: mysql:8.0.37
    networks:
      - internal_net
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: client_management
      MYSQL_HOST: db
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
    networks:
      - internal_net
    ports:
      - "8000:8000"

version: "3"
volumes:
  db_data:
