name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push stock management image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/stock_management:latest ./stock_management
          docker push ${{ secrets.DOCKER_USERNAME }}/stock_management:latest

      - name: Build and push client management image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/client_management:latest ./client_management
          docker push ${{ secrets.DOCKER_USERNAME }}/client_management:latest
