--------------------------------------------
-- Auto-incrémentation d'une clé primaire --
--------------------------------------------

-- A l'aide d'une SEQUENCE et d'un TRIGGER (pas de AUTO_INCREMENT sous Oracle !)
-- Mais depuis Oracle 12g, il existe GENERATED BY DEFAULT AS IDENTITY...

-- numAgence
------------

DROP SEQUENCE seq_Agence;
CREATE SEQUENCE seq_Agence;

CREATE OR REPLACE TRIGGER trig_seq_Agence
BEFORE INSERT ON Agence
FOR EACH ROW
WHEN (NEW.numAgence IS NULL)
BEGIN
	SELECT seq_Agence.NEXTVAL INTO :NEW.numAgence
	FROM DUAL;
END;
/

-- numAgent
-----------

DROP SEQUENCE seq_Agent;
CREATE SEQUENCE seq_Agent;

CREATE OR REPLACE TRIGGER trig_seq_Agent
BEFORE INSERT ON Agent
FOR EACH ROW
WHEN (NEW.numAgent IS NULL)
BEGIN
	SELECT seq_Agent.NEXTVAL INTO :NEW.numAgent
	FROM DUAL;
END;
/

-- numClient
------------

DROP SEQUENCE seq_Client;
CREATE SEQUENCE seq_Client;

CREATE OR REPLACE TRIGGER trig_seq_Client
BEFORE INSERT ON Client
FOR EACH ROW
WHEN (NEW.numClient IS NULL)
BEGIN
	SELECT seq_Client.NEXTVAL INTO :NEW.numClient
	FROM DUAL;
END;
/

-- numCompte
------------

DROP SEQUENCE seq_Compte;
CREATE SEQUENCE seq_Compte;

CREATE OR REPLACE TRIGGER trig_seq_Compte
BEFORE INSERT ON Compte
FOR EACH ROW
WHEN (NEW.numCompte IS NULL)
BEGIN
	SELECT seq_Compte.NEXTVAL INTO :NEW.numCompte
	FROM DUAL;
END;
/

-- numOperation
---------------

DROP SEQUENCE seq_Operation;
CREATE SEQUENCE seq_Operation;

CREATE OR REPLACE TRIGGER trig_seq_Operation
BEFORE INSERT ON Operation
FOR EACH ROW
WHEN (NEW.numOperation IS NULL)
BEGIN
	SELECT seq_Operation.NEXTVAL INTO :NEW.numOperation
	FROM DUAL;
END;
/


----------------------------------
-- Modification de la structure --
----------------------------------

ALTER TABLE Agent
	DROP COLUMN estDirecteur;
	
ALTER TABLE Agence
	ADD sonDirecteur NUMBER
		CONSTRAINT nn_sonDirecteur NOT NULL
		CONSTRAINT uq_sonDirecteur UNIQUE
		CONSTRAINT fk_Agence_Agent REFERENCES Agent(numAgent);