DELETE FROM Apprenti;
DELETE FROM Stagiaire;
DELETE FROM Entreprise;
DELETE FROM Etudiant;
DELETE FROM GroupeInfo1;
DELETE FROM Enseignant;

 


Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('MA','Adam','Michel');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('PB','Baudont','Pascal');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('IB','Borne','Isabelle');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('RF','Fleurquin','Regis');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('TG','Godin','Thibault');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('PJ','Joucla','Philippe');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('GK','Kerbellec','Goulven');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('MLL','Le Lain','Matthieu');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('NLS','Le Sommer','Nicolas');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('SL','Lefevre','Sebastien');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('FL','Lesueur','Francois');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('MM','Mannevy','Muriel');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('FME','Merciol','Francois');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('LN','Naert','Lucie');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('MTP','Pham','Minh-Tan');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('AR','Ridard','Anthony');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('XR','Roirand','Xavier');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('HT','Tuffigo','Helene');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('MV','Volin','Manon');
Insert into ENSEIGNANT (IDENS,NOMENS,PRENOMENS) values ('JFK','Kamp','Jean-Francois');



Insert into GROUPEINFO1 (IDGROUPE,TUTEURGROUPE) values ('A','TG');
Insert into GROUPEINFO1 (IDGROUPE,TUTEURGROUPE) values ('B','HT');
Insert into GROUPEINFO1 (IDGROUPE,TUTEURGROUPE) values ('C','PJ');
Insert into GROUPEINFO1 (IDGROUPE,TUTEURGROUPE) values ('D','MA');



Insert into ETUDIANT (IDETUD,NOMETUD,PRENOMETUD,SEXE,BAC,NOMLYCEE,DEPLYCEE,LEGROUPEINFO1,PARCOURSINFO2,FORMATIONINFO2,POURSUITEETUDES) values (12345678,'TEST','TEST','M','S','LYCEE GENERAL ET TECHNOLOGIQUE X',22,'B','IA','App',null);



Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (1,'ACCENTURE',75);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (2,'ADAPEI56',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (3,'ADM',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (4,'ALADOM',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (5,'ANVERGUR',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (6,'APRAS',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (7,'AWAHOTO',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (8,'BIOTHOT',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (9,'BYSTAMP',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (10,'CADIOU INDUSTRIE',29);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (11,'CAISSE DEPARGNE LOIRE DROME ARDECHE',42);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (12,'CGI',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (13,'CGI',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (14,'CMB',29);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (15,'CNRS',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (16,'COLLEGE SACRE COEUR',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (17,'CONSEIL DEPARTEMENTAL DU MORBIHAN',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (18,'CREDIT AGRICOLE',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (19,'DAVID SYSTEMS GMBH',null);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (20,'DAWIZZ',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (21,'DCODE-IT',27);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (22,'DEPARTEMENT DE LA VENDEE',85);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (23,'DEPARTEMENT DILLE-ET-VILAINE',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (24,'DIOTAL SAS',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (25,'DGFIP',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (26,'DIRISI',29);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (27,'ÉCOLES DE SAINT-CYR COËTQUIDAN',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (28,'ENSIBS',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (29,'ERCII',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (30,'EXOTIC ANIMALS',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (31,'GROUPE ROCHER',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (32,'HIPPOCAD',77);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (33,'HORIZON SYSTEMES DINFORMATION',60);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (34,'IDEMIA',95);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (35,'IFREMER',29);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (36,'INPIXAL',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (37,'INRAE ET FN3PT',75);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (38,'IOLE SOLUTIONS',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (39,'IRISA, EQUIPE OBELIX',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (40,'JEXLPROD',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (41,'JULIANA MULTIMEDIA',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (42,'KARROAD',65);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (43,'LA BIDOUILLERIE',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (44,'LACTALIS',53);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (45,'LEAD OFF',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (46,'LETSEAT',87);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (47,'LUNION DES FORGERONS',91);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (48,'MAIRIE DE SÉNÉ',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (49,'MENBAT',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (50,'MONSTOCK',51);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (51,'NAVAL GROUP',83);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (52,'NIJI',44);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (53,'NIRYO',59);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (54,'NOVOSYS INGENIERIE',88);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (55,'OPTIC PERFORMANCE',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (56,'ORANGE CYBERDÉFENSE',92);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (57,'OUEST BOISSON',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (58,'PLASTEOL',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (59,'PORT DE PÊCHE KEROMAN',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (60,'SCM VIAUD-FORMAGNE',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (61,'SEM LORIENT KEROMAN',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (62,'SIB',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (63,'SITIA',44);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (64,'SMARTMOOV',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (65,'SMURFIT KAPPA FRANCE',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (66,'SOLIDR',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (67,'UBS',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (68,'VIDEOR INFORMATIQUE',56);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (69,'WINNOVE MEDICAL',35);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (70,'WISEBAND',85);
Insert into ENTREPRISE (IDENTREPRISE,NOMENTREPRISE,DEPENTREPRISE) values (71,'YOGOKO',35);


Insert into STAGIAIRE (ETUDSTAGIAIRE,ENTREPRISESTAGE) values (12345678,60);


Insert into APPRENTI (ETUDAPP,ENTREPRISEAPP,TUTEURAPP) values (12345678,71,'MM');
