GPP = g++ -Wall
SRC = ./src
BIN = ./bin

lanceurExo1:
	@echo Compilation lanceurExo1
	$(GPP) $(SRC)/Exo1.cpp -o $(BIN)/Exo1.bin

lanceurExo2:
	@echo Compilation lanceurExo2
	$(GPP) $(SRC)/Exo2.cpp -o $(BIN)/Exo2.bin

lanceurExo3:
	@echo Compilation lanceurExo3
	$(GPP) $(SRC)/Exo3.cpp -o $(BIN)/Exo3.bin
