DROP TABLE EnseignantInfo;
DROP TABLE EtudiantInfo;

CREATE TABLE EnseignantInfo(
		noEns NUMBER(4)
			CONSTRAINT pk_EnseignantInfo PRIMARY KEY,
		nomEns VARCHAR2(20),
		prenom1 VARCHAR2(20),
		prenom2 VARCHAR2(20)
	)
;

INSERT INTO EnseignantInfo VALUES(1,'KAmP','Jean Francois',NULL);
INSERT INTO EnseignantInfo VALUES(2,'BEAuDONT','Pascal','Alexis');
INSERT INTO EnseignantInfo VALUES(3,'GODIN','Thibault','hubert');
INSERT INTO EnseignantInfo VALUES(4,'Lesueur','Francois',NULL);
INSERT INTO EnseignantInfo VALUES(5,'TONIN','Philippe','Fabien');
INSERT INTO EnseignantInfo VALUES(6,'ROIRAND','Xavier','francois');
INSERT INTO EnseignantInfo VALUES(7,'LE SOmMER','Nicolas','Florian');
INSERT INTO EnseignantInfo VALUES(8,'MErCIOL','Francois','hubert');
INSERT INTO EnseignantInfo VALUES(9,'LE Lain','Matthieu',NULL);
INSERT INTO EnseignantInfo VALUES(10,'LEFEVRE','Sebastien','francois');
INSERT INTO EnseignantInfo VALUES(11,'BORNE','Isabelle','lucie');
INSERT INTO EnseignantInfo VALUES(12,'PHAM','Minh Tan','luc');
INSERT INTO EnseignantInfo VALUES(13,'FLEURQUIN','Regis','francois');
INSERT INTO EnseignantInfo VALUES(14,'NAeRT','Lucie','violette');
INSERT INTO EnseignantInfo VALUES(15,'RIDaRD','Anthony','damien');
INSERT INTO EnseignantInfo VALUES(16,'LeMaitre','Elodie',NULL);
INSERT INTO EnseignantInfo VALUES(17,'TUFFIGOT','Helene','coralie');
INSERT INTO EnseignantInfo VALUES(18,'Joucla','Philippe','luc');
INSERT INTO EnseignantInfo VALUES(19,'Kerbellec','Goulven','luc');
INSERT INTO EnseignantInfo VALUES(20,'PHAM','Minh Tan','luc');


CREATE TABLE EtudiantInfo(
		noEtu NUMBER(4)
			CONSTRAINT pk_EtudiantInfo PRIMARY KEY,
		nomEtu VARCHAR2(40),
		prenom VARCHAR2(30),
		promotion varchar(10),
		groupe VARCHAR2(5)
	)
;

INSERT INTO EtudiantInfo VALUES(1,'AGBOGBO (BASSON)','Deborah','INFO1','A');
INSERT INTO EtudiantInfo VALUES(2,'AIME','Raphael','INFO1','B');
INSERT INTO EtudiantInfo VALUES(3,'ANNASRI','Samy','INFO1','A');
INSERT INTO EtudiantInfo VALUES(4,'BARRIAC','Louis','INFO1','D');
INSERT INTO EtudiantInfo VALUES(5,'BASOL','Nathan','INFO1','A');
INSERT INTO EtudiantInfo VALUES(6,'BATARD','Corentin','INFO1','A');
INSERT INTO EtudiantInfo VALUES(7,'BELBEOCH','Ewen','INFO1','D');
INSERT INTO EtudiantInfo VALUES(8,'BELLEC','Alan','INFO1','D');
INSERT INTO EtudiantInfo VALUES(9,'BELLIER','Clement','INFO1','A');
INSERT INTO EtudiantInfo VALUES(10,'BELZ','Youenn','INFO1','B');
INSERT INTO EtudiantInfo VALUES(11,'BOUFFORT','Jean','INFO1','D');
INSERT INTO EtudiantInfo VALUES(12,'BOUILLIS','Awen','INFO1','B');
INSERT INTO EtudiantInfo VALUES(13,'BRAVO','Alexandre','INFO1','B');
INSERT INTO EtudiantInfo VALUES(14,'BRINKHUYSEN','Evy','INFO1','C');
INSERT INTO EtudiantInfo VALUES(15,'CANEVET','Alexandre','INFO1','B');
INSERT INTO EtudiantInfo VALUES(16,'CAOUISSIN','Gwenvael','INFO1','C');
INSERT INTO EtudiantInfo VALUES(17,'CARREAU','Paul-Antoine','INFO1','C');
INSERT INTO EtudiantInfo VALUES(18,'CHARLES','Noe','INFO1','A');
INSERT INTO EtudiantInfo VALUES(19,'CHAVENEAU','Hugo','INFO1','A');
INSERT INTO EtudiantInfo VALUES(20,'CHOFFIN','Paul','INFO1','A');
INSERT INTO EtudiantInfo VALUES(21,'CIVILISE','Gauthier','INFO1','D');
INSERT INTO EtudiantInfo VALUES(22,'COLUSSI','Yohann','INFO1','C');
INSERT INTO EtudiantInfo VALUES(23,'COSSON','Asaiah','INFO1','C');
INSERT INTO EtudiantInfo VALUES(24,'COUDRAY','Sylvain','INFO1','A');
INSERT INTO EtudiantInfo VALUES(25,'DA ROCHA','Gatien','INFO1','B');
INSERT INTO EtudiantInfo VALUES(26,'DAUMARD','Foidjou','INFO1','D');
INSERT INTO EtudiantInfo VALUES(27,'DE CHALENDAR','Alice','INFO1','A');
INSERT INTO EtudiantInfo VALUES(28,'DEBROISE','Esteban','INFO1','A');
INSERT INTO EtudiantInfo VALUES(29,'DELATTRE','Theophile','INFO1','C');
INSERT INTO EtudiantInfo VALUES(30,'DERRIEN','Anatole','INFO1','D');
INSERT INTO EtudiantInfo VALUES(31,'DESSE','Raphael','INFO1','D');
INSERT INTO EtudiantInfo VALUES(32,'DJERBI','Ilies','INFO1','D');
INSERT INTO EtudiantInfo VALUES(33,'ESNAULT','Gabin','INFO1','B');
INSERT INTO EtudiantInfo VALUES(34,'FRANCOIS','Alexis','INFO1','A');
INSERT INTO EtudiantInfo VALUES(35,'GELGON','Lucas','INFO1','D');
INSERT INTO EtudiantInfo VALUES(36,'GERVOT--GUERCHET','Charlie','INFO1','C');
INSERT INTO EtudiantInfo VALUES(37,'GILLE','Swann','INFO1','DEM');
INSERT INTO EtudiantInfo VALUES(38,'GOUAULT--LAMOUR','Camille','INFO1','D');
INSERT INTO EtudiantInfo VALUES(39,'GUEGUEN','Mathis','INFO1','C');
INSERT INTO EtudiantInfo VALUES(40,'GUERNY','Baptiste','INFO1','C');
INSERT INTO EtudiantInfo VALUES(41,'GYS','Theo','INFO1','B');
INSERT INTO EtudiantInfo VALUES(42,'HAMEAU','Nathan','INFO1','DEM');
INSERT INTO EtudiantInfo VALUES(43,'HERMIER','Maxime','INFO1','A');
INSERT INTO EtudiantInfo VALUES(44,'HOCHE--MANIC','Gianni','INFO1','B');
INSERT INTO EtudiantInfo VALUES(45,'HOUSSIN--VONTHRON','Clement','INFO1','A');
INSERT INTO EtudiantInfo VALUES(46,'JEMAI','Axel','INFO1','A');
INSERT INTO EtudiantInfo VALUES(47,'JENN','Melia','INFO1','C');
INSERT INTO EtudiantInfo VALUES(48,'JICQUELLO','Clemence','INFO1','D');
INSERT INTO EtudiantInfo VALUES(49,'JOBE','Matheo','INFO1','B');
INSERT INTO EtudiantInfo VALUES(50,'JONCOUR','Tristan','INFO1','A');
INSERT INTO EtudiantInfo VALUES(51,'KERLOCH','Brieuc','INFO1','DEM');
INSERT INTO EtudiantInfo VALUES(52,'LAPORTE','Julien','INFO1','C');
INSERT INTO EtudiantInfo VALUES(53,'LE BRETON','Thomas','INFO1','C');
INSERT INTO EtudiantInfo VALUES(54,'LE CHANU','Simon','INFO1','C');
INSERT INTO EtudiantInfo VALUES(55,'LE COZ','Erwan','INFO1','');
INSERT INTO EtudiantInfo VALUES(56,'LE DERREY','Lussandre','INFO1','A');
INSERT INTO EtudiantInfo VALUES(57,'LE GUELLEC','Gwendal','INFO1','C');
INSERT INTO EtudiantInfo VALUES(58,'LE JEUNE','Melen','INFO1','D');
INSERT INTO EtudiantInfo VALUES(59,'LE MENN- -FRANKLIN','Eliott','INFO1','B');
INSERT INTO EtudiantInfo VALUES(60,'LE TYRANT','Lenny','INFO1','D');
INSERT INTO EtudiantInfo VALUES(61,'LEBORGNE','Neo','INFO1','B');
INSERT INTO EtudiantInfo VALUES(62,'LEMAITRE','Briac','INFO1','D');
INSERT INTO EtudiantInfo VALUES(63,'LENFANT','Gabriel','INFO1','A');
INSERT INTO EtudiantInfo VALUES(64,'MACCREZ','Allan','INFO1','A');
INSERT INTO EtudiantInfo VALUES(65,'MARREC','Guillaume','INFO1','B');
INSERT INTO EtudiantInfo VALUES(66,'MASSIEU--ROCABOIS','Malo','INFO1','D');
INSERT INTO EtudiantInfo VALUES(67,'MEDJEDOUB','Achraf','INFO1','D');
INSERT INTO EtudiantInfo VALUES(68,'MELLION','Jean-Loup','INFO1','B');
INSERT INTO EtudiantInfo VALUES(69,'MEMAIN','Mael','INFO1','D');
INSERT INTO EtudiantInfo VALUES(70,'MENEZ','Matthys','INFO1','A');
INSERT INTO EtudiantInfo VALUES(71,'MOISY','Damien','INFO1','C');
INSERT INTO EtudiantInfo VALUES(72,'MONBOUSSIN','Dewi','INFO1','D');
INSERT INTO EtudiantInfo VALUES(73,'MONTOIR','Dorian','INFO1','D');
INSERT INTO EtudiantInfo VALUES(74,'MORICE','Guyaume','INFO1','C');
INSERT INTO EtudiantInfo VALUES(75,'MORVAN','Louanne','INFO1','A');
INSERT INTO EtudiantInfo VALUES(76,'NADE','Alexandre','INFO1','D');
INSERT INTO EtudiantInfo VALUES(77,'NICOLAS','Jules','INFO1','B');
INSERT INTO EtudiantInfo VALUES(78,'NOEL--DIVILLER','Amelie','INFO1','B');
INSERT INTO EtudiantInfo VALUES(79,'NOUVION','Mateo','INFO1','C');
INSERT INTO EtudiantInfo VALUES(80,'PABST','Gwendal','INFO1','A');
INSERT INTO EtudiantInfo VALUES(81,'PAVOINE','Oscar','INFO1','C');
INSERT INTO EtudiantInfo VALUES(82,'PERROT','Jean','INFO1','C');
INSERT INTO EtudiantInfo VALUES(83,'PERRUDIN','Mathis','INFO1','B');
INSERT INTO EtudiantInfo VALUES(84,'PIERRE','Noe','INFO1','C');
INSERT INTO EtudiantInfo VALUES(85,'PINEAU','Ludovic','INFO1','A');
INSERT INTO EtudiantInfo VALUES(86,'PINTO DA SILVA','Gabriel','INFO1','C');
INSERT INTO EtudiantInfo VALUES(87,'PITON','Corentin','INFO1','C');
INSERT INTO EtudiantInfo VALUES(88,'PLANTARD','Louis-Marie','INFO1','A');
INSERT INTO EtudiantInfo VALUES(89,'PONT','Jonathan','INFO1','B');
INSERT INTO EtudiantInfo VALUES(90,'PONTGELARD','Thomas','INFO1','C');
INSERT INTO EtudiantInfo VALUES(91,'PUBERT','Elise','INFO1','B');
INSERT INTO EtudiantInfo VALUES(92,'REFREGIER','Theo','INFO1','B');
INSERT INTO EtudiantInfo VALUES(93,'ROBIC','Axel','INFO1','B');
INSERT INTO EtudiantInfo VALUES(94,'ROBIN','Aymeric','INFO1','D');
INSERT INTO EtudiantInfo VALUES(95,'ROGER','Guillaume','INFO1','D');
INSERT INTO EtudiantInfo VALUES(96,'ROMAIN','Axel','INFO1','B');
INSERT INTO EtudiantInfo VALUES(97,'RONARCH','Goulven','INFO1','A');
INSERT INTO EtudiantInfo VALUES(98,'ROUSSEAU','Elouan','INFO1','D');
INSERT INTO EtudiantInfo VALUES(99,'SCAVINER','Killian','INFO1','B');
INSERT INTO EtudiantInfo VALUES(100,'SECRETIN','Nathan','INFO1','B');
INSERT INTO EtudiantInfo VALUES(101,'SEVETTE','Matiss','INFO1','D');
INSERT INTO EtudiantInfo VALUES(102,'STEPHAN','Mathieu','INFO1','A');
INSERT INTO EtudiantInfo VALUES(103,'SZCZEPANSKI','Serge','INFO1','D');
INSERT INTO EtudiantInfo VALUES(104,'UZEL','Ronan','INFO1','D');
INSERT INTO EtudiantInfo VALUES(105,'VAAL','Simon','INFO1','C');
INSERT INTO EtudiantInfo VALUES(106,'VALLEE','Matheo','INFO1','B');
INSERT INTO EtudiantInfo VALUES(107,'VIDAL','Titouan','INFO1','C');
INSERT INTO EtudiantInfo VALUES(108,'BEATRIX','Jeremy','INFO2','A');
INSERT INTO EtudiantInfo VALUES(109,'BENDRAOU','Ayoub','INFO2','C');
INSERT INTO EtudiantInfo VALUES(110,'BERTRAND','Sophie','INFO2','B');
INSERT INTO EtudiantInfo VALUES(111,'BESILY','Michael','INFO2','A');
INSERT INTO EtudiantInfo VALUES(112,'BOSSARD','Lucas','INFO2','C');
INSERT INTO EtudiantInfo VALUES(113,'BOUNIOT','Yanis','INFO2','B');
INSERT INTO EtudiantInfo VALUES(114,'BOURBIGOT','Tristan','INFO2','A');
INSERT INTO EtudiantInfo VALUES(115,'CARTIER','Matis','INFO2','C');
INSERT INTO EtudiantInfo VALUES(116,'CHARGE','Maxime','INFO2','B');
INSERT INTO EtudiantInfo VALUES(117,'COMBES','Marius','INFO2','B');
INSERT INTO EtudiantInfo VALUES(118,'COSTAMAGNA','Baptiste','INFO2','A');
INSERT INTO EtudiantInfo VALUES(119,'DANEL','Loris','INFO2','C');
INSERT INTO EtudiantInfo VALUES(120,'DELANNOY','Gwenvael','INFO2','A');
INSERT INTO EtudiantInfo VALUES(121,'DISCAZEAUX','Mattis','INFO2','B');
INSERT INTO EtudiantInfo VALUES(122,'DUMOULIN','Tobias','INFO2','C');
INSERT INTO EtudiantInfo VALUES(123,'FLEJOU','Mateo','INFO2','B');
INSERT INTO EtudiantInfo VALUES(124,'FOULON','Sam','INFO2','C');
INSERT INTO EtudiantInfo VALUES(125,'GAUTHIER','Jules','INFO2','B');
INSERT INTO EtudiantInfo VALUES(126,'GORRE','Romain','INFO2','C');
INSERT INTO EtudiantInfo VALUES(127,'GRANIER','Gabriel','INFO2','C');
INSERT INTO EtudiantInfo VALUES(128,'GUILLOME','Benjamin','INFO2','A');
INSERT INTO EtudiantInfo VALUES(129,'HASCOET','Anthony','INFO2','B');
INSERT INTO EtudiantInfo VALUES(130,'HYEANS','Matthieu','INFO2','A');
INSERT INTO EtudiantInfo VALUES(131,'JAMARD','Youenn','INFO2','C');
INSERT INTO EtudiantInfo VALUES(132,'JAMET','Titouan','INFO2','A');
INSERT INTO EtudiantInfo VALUES(133,'JAMETTI','Nolan','INFO2','B');
INSERT INTO EtudiantInfo VALUES(134,'JEANNE','Stevan','INFO2','A');
INSERT INTO EtudiantInfo VALUES(135,'JOLY-JEHENNE','Leo','INFO2','B');
INSERT INTO EtudiantInfo VALUES(136,'JOMAA','Nael','INFO2','');
INSERT INTO EtudiantInfo VALUES(137,'KERBOUS','Chadene','INFO2','C');
INSERT INTO EtudiantInfo VALUES(138,'LAGREE','Titouan','INFO2','A');
INSERT INTO EtudiantInfo VALUES(139,'LARGILLET','Thomas','INFO2','B');
INSERT INTO EtudiantInfo VALUES(140,'LE BODO','Enzo','INFO2','C');
INSERT INTO EtudiantInfo VALUES(141,'LE BOUEDEC','Benjamin','INFO2','B');
INSERT INTO EtudiantInfo VALUES(142,'LE BUAN','Mewenn','INFO2','A');
INSERT INTO EtudiantInfo VALUES(143,'LE GOFF LE GREVELLEC','Hugo','INFO2','B');
INSERT INTO EtudiantInfo VALUES(144,'LE NOE','Hugo','INFO2','B');
INSERT INTO EtudiantInfo VALUES(145,'LE POUPON','Matteo','INFO2','B');
INSERT INTO EtudiantInfo VALUES(146,'LE ROUX','Erwan','INFO2','A');
INSERT INTO EtudiantInfo VALUES(147,'MADEC','Yanis','INFO2','A');
INSERT INTO EtudiantInfo VALUES(148,'MAILLET','CLeMENT','INFO2','B');
INSERT INTO EtudiantInfo VALUES(149,'MALIVET','Ervan','INFO2','B');
INSERT INTO EtudiantInfo VALUES(150,'MARGHICH','Hamza','INFO2','B');
INSERT INTO EtudiantInfo VALUES(151,'MARSOLIER','Efflam','INFO2','A');
INSERT INTO EtudiantInfo VALUES(152,'MASSON','Damien','INFO2','A');
INSERT INTO EtudiantInfo VALUES(153,'MICHON','Peter','INFO2','C');
INSERT INTO EtudiantInfo VALUES(154,'MILLET','Jessica','INFO2','C');
INSERT INTO EtudiantInfo VALUES(155,'MONFORT','Clement','INFO2','B');
INSERT INTO EtudiantInfo VALUES(156,'MONTIEGE','Hugo','INFO2','A');
INSERT INTO EtudiantInfo VALUES(157,'NOUGUES','Nolann','INFO2','A');
INSERT INTO EtudiantInfo VALUES(158,'OBIN','Jonathan','INFO2','C');
INSERT INTO EtudiantInfo VALUES(159,'OFFREDI','Eve-Anne','INFO2','A');
INSERT INTO EtudiantInfo VALUES(160,'OZANNE','Colin','INFO2','A');
INSERT INTO EtudiantInfo VALUES(161,'PERON','Yann-Mael','INFO2','C');
INSERT INTO EtudiantInfo VALUES(162,'PERREL--LE JALLE','Hugo','INFO2','B');
INSERT INTO EtudiantInfo VALUES(163,'PHILIPPE','Mael','INFO2','B');
INSERT INTO EtudiantInfo VALUES(164,'POGU','Anthony','INFO2','C');
INSERT INTO EtudiantInfo VALUES(165,'POULAIN','Theo','INFO2','A');
INSERT INTO EtudiantInfo VALUES(166,'POULAIN','Thomas','INFO2','A');
INSERT INTO EtudiantInfo VALUES(167,'QUERE','Romain','INFO2','C');
INSERT INTO EtudiantInfo VALUES(168,'RAGUENEAU','William','INFO2','A');
INSERT INTO EtudiantInfo VALUES(169,'TABOR','Samuel','INFO2','B');
INSERT INTO EtudiantInfo VALUES(170,'TORRI','Lucas','INFO2','C');
INSERT INTO EtudiantInfo VALUES(171,'TOULEMONT','Arwen','INFO2','B');
INSERT INTO EtudiantInfo VALUES(172,'UZUN','Baki','INFO2','C');
INSERT INTO EtudiantInfo VALUES(173,'WADOUX','Felix','INFO2','A');
INSERT INTO EtudiantInfo VALUES(174,'ANTONIO','Emy','INFO2','D');
INSERT INTO EtudiantInfo VALUES(175,'AUGER','Mateo','INFO2','D');
INSERT INTO EtudiantInfo VALUES(176,'BOISSEL','Francois','INFO2','D');
INSERT INTO EtudiantInfo VALUES(177,'BORGHI','Alexandre','INFO2','D');
INSERT INTO EtudiantInfo VALUES(178,'BOUTEMY','Thomas','INFO2','D');
INSERT INTO EtudiantInfo VALUES(179,'CHALLON','Theo','INFO2','D');
INSERT INTO EtudiantInfo VALUES(180,'FAUCHE','Theo','INFO2','D');
INSERT INTO EtudiantInfo VALUES(181,'GICQUEL','Baptiste','INFO2','D');
INSERT INTO EtudiantInfo VALUES(182,'GOURMELEN','Tom','INFO2','D');
INSERT INTO EtudiantInfo VALUES(183,'GUEGAN','Anna','INFO2','D');
INSERT INTO EtudiantInfo VALUES(184,'HASCOET','Jack','INFO2','D');
INSERT INTO EtudiantInfo VALUES(185,'LE BARS','Florian','INFO2','D');
INSERT INTO EtudiantInfo VALUES(186,'LE GAL','Elvin','INFO2','D');
INSERT INTO EtudiantInfo VALUES(187,'LE NY','Liam','INFO2','D');
INSERT INTO EtudiantInfo VALUES(188,'LE ROY','Pierre-Jean','INFO2','D');
INSERT INTO EtudiantInfo VALUES(189,'LUCAS','Elouann','INFO2','D');
INSERT INTO EtudiantInfo VALUES(190,'MEZIRARD','Flavien','INFO2','D');
INSERT INTO EtudiantInfo VALUES(191,'MORICE--LEGOUET','DaMIen','INFO2','D');
INSERT INTO EtudiantInfo VALUES(192,'MORVAN','Enzo','INFO2','D');
INSERT INTO EtudiantInfo VALUES(193,'NOEL','Andy','INFO2','D');
INSERT INTO EtudiantInfo VALUES(194,'PASQUIER','Augustin','INFO2','D');
INSERT INTO EtudiantInfo VALUES(195,'POSSELT','Timothee','INFO2','D');
INSERT INTO EtudiantInfo VALUES(196,'SALINAS','Thomas','INFO2','D');
INSERT INTO EtudiantInfo VALUES(197,'SERGENT','Tanguy','INFO2','D');