server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password:
    url: jdbc:h2:mem:locationdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
